=== vishnunairjanardhan/democms/.astro/collections/authors.schema.json
{
  "$ref": "#/definitions/authors",
  "definitions": {
    "authors": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "img": {
          "type": "string"
        },
        "bio": {
          "type": "string"
        },
        "designation": {
          "type": "string"
        },
        "twitter": {
          "type": "string"
        },
        "linkedin": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "img"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== vishnunairjanardhan/democms/src/content/authors/Soniya.json
{
  "name": "Soniya",
  "img": "/assets/testimonial/Soniya.webp",
  "bio": "Soniya is a digital marketing strategist with 5+ years of experience. She specializes in SEO and content driven marketing. She is passionate about enhancing brand visibility. She specializes in social media marketing and content creation.",
  "designation": "Marketing Strategist",
  "twitter": "https://x.com/SoniyaDixit21",
  "linkedin": "https://www.linkedin.com/in/dixit-soniya/"
}

=== vishnunairjanardhan/democms/src/content/authors/Pravin.json
{
  "name": "Pravin",
  "img": "/assets/testimonial/Pravin.png",
  "bio": "Pravin is our CEO and Co-Founder with decades of experience in the tech industry. He is dedicated to driving innovation and excellence in all our projects. He is passionate about leading teams to success.",
  "designation": "CEO & Co-Founder",
  "twitter": "https://twitter.com/pravinkamble",
  "linkedin": "https://www.linkedin.com/in/pravinkamble/"
}

=== vishnunairjanardhan/democms/src/content/authors/Piyush.json
{
  "name": "Piyush",
  "img": "/assets/testimonial/Piyush.webp",
  "bio": "Piyush is a digital marketing strategist with 5+ years of experience. He specializes in AI-driven marketing solutions. He is passionate about helping businesses grow online. He specializes in copeptive analysis and GEO.",
  "designation": "Marketing Strategist",
  "twitter": "https://twitter.com/PiyushSingh",
  "linkedin": "https://www.linkedin.com/in/piyush-singh-275632222/"
}

=== vishnunairjanardhan/democms/src/content/authors/Mrudul.json
{
  "name": "Mrudul",
  "img": "/assets/testimonial/Mrudul.png",
  "bio": "Mrudul is our CTO with 10+ years of experience in tech. He leads our development team. He is passionate about building scalable solutions. He is an advocate for clean code and best practices.",
  "designation": "CTO & Co-Founder",
  "twitter": "https://twitter.com/mrudult",
  "linkedin": "https://www.linkedin.com/in/mrudult/"
}
